project: QU4-MLP
device: cuda:0
net: model.MLP
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 100
batch_size: 256
seeds: [89, 231, 928]
net_config:
  nodes: 64
  layers: 4
optimizer_config:
  lr: 1.e-3 # Must contain dot for float
scheduler_config:
  upper_bound: 250
  max_iter: 100
  infimum_lr: 1.e-5
early_stopping_config:
  enabled: false
  patience: 10
  mode: min # 'min' or 'max'
  min_delta: 0.0001 # Percent
