project: QU4-MLP
device: cuda:0
net: model.MLP
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 256
seeds: [89, 231, 928]
net_config:
  nodes: 128
  layers: 4
optimizer_config:
  lr: 0.006278654119219496
scheduler_config:
  upper_bound: 350
  max_iter: 250
  infimum_lr: 0.0000038940820621337
early_stopping_config:
  enabled: false
  patience: 10
  mode: min # 'min' or 'max'
  min_delta: 0.0001 # Percent
